name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 0"
  push:
    branches: [ master ]
    paths-ignore:
      - "**/README.md"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANTIFILTER_DOWNLOAD: https://community.antifilter.download/list/domains.lst
      REFILTER_ALL: https://raw.githubusercontent.com/1andrevich/Re-filter-lists/refs/heads/main/domains_all.lst

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          path: code

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: code/go.mod

      - name: Set release tags
        run: |
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Download data lists
        run: |
          mkdir -p data
          curl --fail -s -o data/category-ru \
            https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/category-ru
          curl --fail -s -o data/private \
            https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/private || true
          grep '^include:' data/category-ru \
            | cut -d':' -f2 \
            | while read -r f; do
                curl --fail -s -o data/"$f" \
                  https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/"$f" || true
              done

      - name: Build Russia blocklist
        run: |
          mkdir -p filtered
          curl -sSL "$ANTIFILTER_DOWNLOAD" -o filtered/antifilter.lst
          curl -sSL "$REFILTER_ALL" -o filtered/refilter.lst
          cat filtered/antifilter.lst filtered/refilter.lst | grep -E '\.(ru|su|xn--80adxhks|xn--80asehdb|xn--80aswg|xn--c1avg|xn--d1acj3b|xn--p1acf|xn--p1ai)$' | sort | uniq > data/category-ban-ru

      - name: Build geosite.dat
        run: |
          mkdir -p release
          cd code
          go mod tidy
          go run main.go \
            --datapath=../data \
            --outputdir=../release \
            --exportlists=category-ban-ru,category-ru,private
          cd ..
          ls -R

      - name: Generate geosite.dat sha256 hash
        run: |
          sha256sum release/geosite.dat > release/geosite.dat.sha256sum
          cat release/geosite.dat.sha256sum

      - name: Create release and upload geosite.dat
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$TAG_NAME" release/geosite.dat release/geosite.dat.sha256sum \
            --repo $GITHUB_REPOSITORY \
            --title "$RELEASE_NAME" \
            --notes "" \
            --draft=false \
            --prerelease=false
